# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.allowed_synced_folder_types = [:rsync]

  config.vm.provider :aws do |aws, override|
    aws.access_key_id     = "ACCESS_KEY"
    aws.secret_access_key = "SECRET_ACCESS_KEY"
    aws.keypair_name      = "SSH_KEY_PAIR"

    aws.region            = "eu-west-1"
    aws.instance_type     = "t2.medium"
    aws.ami               = "ami-0e12cbde3e77cbb98" #RedHat 7.6
    aws.security_groups   = "SECURITY_GROUP"


    aws.tags = {
        "Name"    => "puppetoss",
        "Creator" => 'vagrant',
    }

    override.ssh.username         = "ec2-user"
    override.ssh.private_key_path = "~/.ssh/PRIV_SSH_KEY"
  end

  config.vm.provision 'shell', path: 'install.sh'
end
