source ENV['GEM_SOURCE'] || 'https://rubygems.org'

group :test do
  gem 'rake',                   :require => false
  gem 'puppetlabs_spec_helper', :require => false
  gem 'metadata-json-lint',     :require => false
  gem 'semantic_puppet',        :require => false
  gem 'rspec-its',              :require => false
  gem 'rspec-puppet-facts',     :require => false
end

# vim:ft=ruby
